FROM node:alpine

WORKDIR "/app"
ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent
RUN npm config set unsafe-perm true


COPY . .

CMD ["npm", "start"]